---
name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download
      uses: dawidd6/action-download-artifact@v3
      with:
        name: my-artifact-new
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme  # Install Sphinx and a theme, adjust as necessary
        # Add other dependencies if required

    - name: Generate API documentation
      run: |
        sudo apt update
        sudo apt --fix-broken install
        sudo apt install -y libunwind-dev libprotobuf-dev libhdf5-serial-dev libgoogle-perftools-dev
        build/ALL/gem5.opt gem5-sphinx-apidoc -o docs src/python/gem5 -F -e
      
    - name: Build the documentation
      run: |
        SPHINXBUILD="build/ALL/gem5.opt gem5-sphinx" make -C docs html
